### ISSUE TITLE
It would be nice to override css defaults for buttons. Unable to just add css property. It does not pick them up.

### ISSUE THREAD

**Issue by bobsov** [Jaspero/ng-confirmations#13]
Not an issue but more of a way to customize/override buttons css property.

**Comment by flauc** [comment]
That's strange. The components have `ViewEncapsulation.None`. This for example works nicely: 

```css
.primary {
  background: blue !important;
}
```
